### ISSUE TITLE
Remove secret from source code

### ISSUE THREAD

**Issue by MarcusRohr** [SwiftFortune/easypoe#1]
https://github.com/SwiftFortune/easypoe/blob/master/backend/backend/settings.py#L23

Should be moved into a config file on your server.

Also see the comment to this line:
https://github.com/SwiftFortune/easypoe/blob/master/backend/backend/settings.py#L26

**Comment by SwiftFortune** [comment]
Thank you for pointing that out. I have a separate project source with those files related to deployment changed/removed. I intend to leave this project source as is so that I can it immediately run it on localhost.

There is some weird bug with Django when Debug is turned off. It can't for some reason serve static file when debug is turned off. You can see the thread here: 

https://github.com/heroku-python/dj-static/issues/11
